name: publish-webgl
description: "Package and publish a WebGL version"

inputs:
  itchio_api_key: 
    description: 'Itch.io API key for publishing'
    required: true
  itchio_username: 
    description: 'Itch.io user-name'
    required: true
  itchio_game_id: 
    description: 'Itch.io game-id'
    required: true
  itchio_build_channel: 
    description: 'Itch.io build-channel'
    default: browser

runs:
  using: "composite"
  steps:

    - uses: actions/download-artifact@v3
      with:
        name: user-minidisk

    - name: Download MiniMicro WebGL template
      run: wget --no-verbose -O minimicro-webgl.zip https://miniscript.org/files/minimicro-webgl.zip
      shell: bash

    - name: Unzip WebGL template
      run: unzip minimicro-webgl.zip -d minimicro-web
      shell: bash
    
    - name: Move user.minidisk
      run: mv user.minidisk ./minimicro-web/MiniMicro/StreamingAssets/
      shell: bash

    - name: Publish WebGL template to itch.io
      uses: KikimoraGames/itch-publish@v0.0.3
      with:
        butlerApiKey: ${{ inputs.itchio_api_key }}
        gameData: ./minimicro-web/MiniMicro
        itchUsername: ${{ inputs.itchio_username }}
        itchGameId: ${{ inputs.itchio_game_id }}
        buildChannel: ${{ inputs.itchio_build_channel }}
