name: publish-linux
description: "Package and publish a Linux version"

inputs:
  itchio_api_key: 
    description: 'Itch.io API key for publishing'
    required: true
  itchio_username: 
    description: 'Itch.io user-name'
    required: true
  itchio_game_id: 
    description: 'Itch.io game-id'
    required: true

runs:
  using: "composite"
  steps:

    - name: Restore user-minidisk artifact
      uses: actions/download-artifact@v3
      with:
        name: user-minidisk

    - name: Resolve template hash-code
      run: |
        HEAD=$(curl --silent --head https://miniscript.org/files/minimicro-linux.tar.gz)
        ETAG=$(echo "$HEAD" | grep "ETag")
        ETAG=${ETAG//[$'\t\r\n']}
        TEMPLATE_HASH=$(echo $ETAG | awk '{gsub(/"/, "", $2); print $2}')
        echo "Using TEMPLATE_HASH: \"${TEMPLATE_HASH}\""
        echo "TEMPLATE_HASH=\"$TEMPLATE_HASH\"" >> $GITHUB_ENV
      shell: bash

    - name: Cache template file
      uses: actions/cache@v3
      id: cache-linux-template
      env:
          cache-name: cache-minimicro-templates
      with:
        path: minimicro-linux.tar.gz
        key: ${{ env.TEMPLATE_HASH }}

    - name: Download Linux template
      if: ${{ steps.cache-linux-template.outputs.cache-hit != 'true' }}
      run: wget --no-verbose -O minimicro-linux.tar.gz https://miniscript.org/files/minimicro-linux.tar.gz
      shell: bash

    - name: Unpack Linux template
      run: |
        mkdir -p ./minimicro-linux
        tar -xvf minimicro-linux.tar.gz -C ./minimicro-linux
      shell: bash

    - name: Copy user.minidisk
      run: cp user.minidisk ./minimicro-linux
      shell: bash

    #- name: Publish Linux template to itch.io
    #  uses: KikimoraGames/itch-publish@v0.0.3
    #  with:
    #    butlerApiKey: ${{ inputs.itchio_api_key }}
    #    gameData: ./minimicro-linux
    #    itchUsername: ${{ inputs.itchio_username }}
    #    itchGameId: ${{ inputs.itchio_game_id }}
    #    buildChannel: linux
