name: publish-webgl
description: "Package and publish a Windows version"

inputs:
  itchio_api_key: 
    description: 'Itch.io API key for publishing'
    required: true
  itchio_username: 
    description: 'Itch.io user-name'
    required: true
  itchio_game_id: 
    description: 'Itch.io game-id'
    required: true

runs:
  using: "composite"
  steps:

    - name: Restore user-minidisk artifact
      uses: actions/download-artifact@v3
      with:
        name: user-minidisk

    - name: Resolve template hash-code
      run: |
        HEAD=$(curl --silent --head https://miniscript.org/files/minimicro-win.zip)
        ETAG=$(echo "$HEAD" | grep "ETag")
        ETAG=${ETAG//[$'\t\r\n']}
        TEMPLATE_HASH=$(echo $ETAG | awk '{gsub(/"/, "", $2); print $2}')
        echo "Using TEMPLATE_HASH: \"${TEMPLATE_HASH}\""
        echo "TEMPLATE_HASH=$TEMPLATE_HASH" >> $GITHUB_ENV
      shell: bash

    - name: Cache template file
      uses: actions/cache@v3
      id: cache-win-template
      env:
          cache-name: cache-win-template
      with:
        path: minimicro-win.zip
        key: windows-${{ env.TEMPLATE_HASH }}

    - name: Download Windows template
      if: ${{ steps.cache-win-template.outputs.cache-hit != 'true' }}
      run: wget --no-verbose -O minimicro-win.zip https://miniscript.org/files/minimicro-win.zip
      shell: bash

    - name: Unzip Windows template
      run: unzip minimicro-win.zip -d minimicro-win
      shell: bash

    - name: Move user.minidisk
      run: mv user.minidisk ./minimicro-win/MiniMicro
      shell: bash

    #- name: Publish Windows template to itch.io
    #  uses: KikimoraGames/itch-publish@v0.0.3
    #  with:
    #    butlerApiKey: ${{ inputs.itchio_api_key }}
    #    gameData: ./minimicro-win/MiniMicro
    #    itchUsername: ${{ inputs.itchio_username }}
    #    itchGameId: ${{ inputs.itchio_game_id }}
    #    buildChannel: windows
