name: Build and publish to itch.io

on:
  workflow_call:
    inputs:
      minidisk_main_file:
        required: true
        type: string
      minidisk_additional_entries:
        required: false
        type: string
      boot_opts_path:
        required: false
        type: string
      custom_executable_name:
        description: "Name to use for executable - optional"
        required: false
        type: string
      itch_io_username:
        required: true
        type: string
      itch_io_game_id:
        required: true
        type: string
      itchio_web_channel:
        type: string
        required: false
        default: browser
    secrets:
      itch_io_api_key:
        required: true

# Note how because this is a reusable workflow and runs in the
# context of the caller, the composite actions (local to this
# workflow) have to be referenced absolutely.

jobs:

  prepare-assets:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: sebnozzi/minimicro-actions/.github/actions/build-minidisk@main
        with:
          main_file: ${{ inputs.minidisk_main_file }}
          additional_entries: ${{ inputs.minidisk_additional_entries }}
      - uses: sebnozzi/minimicro-actions/.github/actions/upload-boot-opts@main
        with:
          boot_opts_path: ${{ inputs.boot_opts_path }}

  build-and-publish-webgl:
    needs: prepare-assets
    runs-on: ubuntu-latest    
    steps:
      - uses: actions/checkout@v3
      - uses: sebnozzi/minimicro-actions/.github/actions/publish-webgl@main
        with:
          itchio_api_key: ${{ secrets.itch_io_api_key }}
          itchio_username: ${{ inputs.itch_io_username }}
          itchio_game_id: ${{ inputs.itch_io_game_id }}
          itchio_build_channel: ${{ inputs.itchio_web_channel }}

  build-and-publish-windows:
    needs: prepare-assets
    runs-on: ubuntu-latest    
    steps:
      - uses: actions/checkout@v3
      - uses: sebnozzi/minimicro-actions/.github/actions/publish-windows@main
        with:
          itchio_api_key: ${{ secrets.itch_io_api_key }}
          itchio_username: ${{ inputs.itch_io_username }}
          itchio_game_id: ${{ inputs.itch_io_game_id }}
          custom_executable_name: ${{ inputs.custom_executable_name }}

  build-and-publish-mac:
    needs: prepare-assets
    runs-on: ubuntu-latest    
    steps:
      - uses: actions/checkout@v3
      - uses: sebnozzi/minimicro-actions/.github/actions/publish-mac@main
        with:
          itchio_api_key: ${{ secrets.itch_io_api_key }}
          itchio_username: ${{ inputs.itch_io_username }}
          itchio_game_id: ${{ inputs.itch_io_game_id }}
          custom_executable_name: ${{ inputs.custom_executable_name }}

  build-and-publish-linux:
    needs: prepare-assets
    runs-on: ubuntu-latest    
    steps:
      - uses: actions/checkout@v3
      - uses: sebnozzi/minimicro-actions/.github/actions/publish-linux@main
        with:
          itchio_api_key: ${{ secrets.itch_io_api_key }}
          itchio_username: ${{ inputs.itch_io_username }}
          itchio_game_id: ${{ inputs.itch_io_game_id }}
          custom_executable_name: ${{ inputs.custom_executable_name }}
